### ISSUE TITLE
Fresh install gives OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tim-jones-001** [deanishe/alfred-mpd#3]
Just installed (on macbook pro running high sierra) and get following error:

debug output :
```
2017-11-10 15:54:51][ERROR: input.scriptfilter] Code 1: 15:54:51 workflow.py:2225 DEBUG    Workflow version : 0.1.2
15:54:51 workflow.py:1628 DEBUG    Reading settings from `/Users/tim/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred.mpd/settings.json` ...
15:54:51 workflow.py:2514 DEBUG    Update check not due
15:54:51 ampd:686 DEBUG    opts={'--help': False,
 '--version': False,
 '<action>': None,
 '<query>': u'',
 'do': False,
 'search': True,
 'stats': False,
 'status': False}
15:54:51 ampd:687 DEBUG    mpd: host=localhost, port=6600
15:54:51 workflow.py:1859 DEBUG    Loading cached data from : /Users/tim/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred.mpd/__workflow_update_status.cpickle
15:54:51 workflow.py:2444 DEBUG    update_data : {u'available': True, u'version': u'v0.1.3', u'download_url': u'https://github.com/deanishe/alfred-mpd/releases/download/v0.1.3/MPD-0.1.3.alfredworkflow'}
15:54:51 mpd.py:140 DEBUG    mpc command: ['stats']
15:54:51 workflow.py:2243 ERROR    [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ECCC0F1B-1C25-458F-8FA6-E17948FAC636/lib/workflow/workflow.py", line 2236, in run
    func(self)
  File "./ampd", line 691, in main
    return do_search(opts)
  File "./ampd", line 485, in do_search
    return do_stats(opts)
  File "./ampd", line 614, in do_stats
    st = mpd.stats()
  File "/Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ECCC0F1B-1C25-458F-8FA6-E17948FAC636/lib/mpd.py", line 260, in stats
    for line in mpc('stats').splitlines():
  File "/Users/tim/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ECCC0F1B-1C25-458F-8FA6-E17948FAC636/lib/mpd.py", line 144, in mpc
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
15:54:51 workflow.py:2246 INFO     For assistance, see: https://github.com/deanishe/alfred-mpd/issues
15:54:51 workflow.py:2267 DEBUG    Workflow finished in 0.043 seconds.
```

**Comment by deanishe** [comment]
Have you installed `mpc` with Homebrew?

**Comment by tim-jones-001** [comment]
Thanks for your reply - installed mpd (and ncmpcpp) by homebrew, but did
not install mpc at all

**Comment by deanishe** [comment]
So that fixed it?

**Comment by tim-jones-001** [comment]
Thanks very much for your reply and sorry for my delay in response

I installed mpc separately and that indeed did fix it

Thanks

Tim

**Comment by deanishe** [comment]
Grand.
