### ISSUE TITLE
Controlling remote MPD server

### ISSUE THREAD

**Issue by jondoesntgit** [deanishe/alfred-mpd#4]
Hey,

I'm trying to control a remote MPD server using your script. I've changed the URL and PORT, and the error has now changed from "directory not found" to "execv() arg 2 must contain only strings."

Here's the stack trace....

    Starting debug for 'MPD'
    
    [2018-04-06 08:49:18][ERROR: input.scriptfilter] Code 1: 08:49:18 workflow.py:2225 DEBUG    Workflow version : 0.1.3
    08:49:18 workflow.py:1628 DEBUG    Reading settings from `/Users/wheelerj/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred.mpd/settings.json` ...
    08:49:18 workflow.py:2514 DEBUG    Update check not due
    08:49:18 ampd:689 DEBUG    opts={'--help': False,
     '--version': False,
     '<action>': None,
     '<query>': u'',
     'do': False,
     'search': True,
     'stats': False,
     'status': False}
    08:49:18 ampd:690 DEBUG    mpd: host=192.168.0.95, port=6680
    08:49:18 workflow.py:1859 DEBUG    Loading cached data from : /Users/wheelerj/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred.mpd/__workflow_update_status.cpickle
    08:49:18 workflow.py:2444 DEBUG    update_data : {u'available': False}
    08:49:18 mpd.py:140 DEBUG    mpc command: ['stats']
    08:49:18 workflow.py:2243 ERROR    execv() arg 2 must contain only strings
    Traceback (most recent call last):
      File "/Users/wheelerj/Dropbox/archive/alfred/Alfred.alfredpreferences/workflows/user.workflow.BD11304E-09A9-4E24-ABC7-58A06AACC1CD/lib/workflow/workflow.py", line 2236, in run
        func(self)
      File "./ampd", line 694, in main
        return do_search(opts)
      File "./ampd", line 485, in do_search
        return do_stats(opts)
      File "./ampd", line 614, in do_stats
        st = mpd.stats()
      File "/Users/wheelerj/Dropbox/archive/alfred/Alfred.alfredpreferences/workflows/user.workflow.BD11304E-09A9-4E24-ABC7-58A06AACC1CD/lib/mpd.py", line 260, in stats
        for line in mpc('stats').splitlines():
      File "/Users/wheelerj/Dropbox/archive/alfred/Alfred.alfredpreferences/workflows/user.workflow.BD11304E-09A9-4E24-ABC7-58A06AACC1CD/lib/mpd.py", line 144, in mpc
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    TypeError: execv() arg 2 must contain only strings
    08:49:18 workflow.py:2246 INFO     For assistance, see: https://github.com/deanishe/alfred-mpd/issues
    08:49:18 workflow.py:2267 DEBUG    Workflow finished in 0.071 seconds.

**Comment by jondoesntgit** [comment]
Never mind. I needed to install `mpc` first.
